### ISSUE TITLE
"gh auth login" not working in the Action. 

### ISSUE THREAD

**Issue by bdougie** [domitriusclark/mdnext#40]
Hey, hope you don't mind me dropping this issue on the Action failure. 

https://github.com/domitriusclark/mdnext/runs/1114016579?check_suite_focus=true

## Trying to get context.

I see you have the token in your [workflow](https://github.com/domitriusclark/mdnext/blob/master/.github/workflows/publish.yml). 

```yml
      - uses: ./.github/actions/hub-create-repos
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
``` 

But I don't see you using it in [hub-create-repos](https://github.com/domitriusclark/mdnext/blob/master/.github/actions/hub-create-repos/index.js#L7) Action.

## My suggestion without context would have been

per the latest [release](https://github.com/cli/cli/pull/1445): `gh auth login --with-token process.env.GITHUB_TOKEN`

Let me know if I am missing something. 

_ example from the PR in the cli repo_
![gh auth login --with-token example](https://user-images.githubusercontent.com/98482/88857447-e936e580-d1bb-11ea-93b6-ed9801c2517c.gif)
